name: terrabayt_uz
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  get_it: ^7.2.0
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.0+1
  chips_choice: ^3.0.0
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  flutter_widget_from_html: ^0.10.0
  webview_flutter: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/lola.jpg
